# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < https://docs.platformio.org/page/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < https://docs.platformio.org/page/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < https://docs.platformio.org/page/userguide/cmd_ci.html >
#
#

language: python
python:
  - "2.7"
dist: trusty
sudo: required
jdk:
  - oraclejdk8

cache:
  directories:
    - "~/.platformio"
    - '$HOME/.sonar/cache'

install:
  - pip install -U platformio
  - platformio update  
  - platformio lib install 1
  - platformio lib install DallasTemperature
  - platformio lib install Cayenne-MQTT-ESP
  - platformio lib install thinger.io

#script:
#  - platformio run

addons:
  sonarcloud:
    organization: "oxydation-github" # the key of the org you chose at step #3
    token:
      secure: "1ed2602e7cf137a7624be7db24d721da75870bb6" # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - build-wrapper-linux-x86-64 --out-dir bw_output platformio run
  - sonar-scanner